# Generated by Django 4.0.4 on 2022-05-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Culture',
        ),
    ]
