# Generated by Django 4.0.4 on 2022-05-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_rename_news_culture'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posteo'),
        ),
    ]
