# Generated by Django 4.0.4 on 2022-05-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_culture_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='economy',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posteo'),
        ),
        migrations.AddField(
            model_name='sports',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posteo'),
        ),
    ]
