# Generated by Django 4.0.4 on 2022-05-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_economy_imagen_sports_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posteo', models.ImageField(blank=True, null=True, upload_to='posteos')),
            ],
        ),
    ]
