# Generated by Django 4.0.4 on 2022-05-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='campo',
            field=models.CharField(max_length=250),
        ),
    ]
